
This notebook will be a place to learn or just a documentation of how I learnt about PyTorch 🔥


In [1]:
import torch
import pandas
import numpy
import matplotlib.pyplot as plt

In [2]:
# creates a scalar with the value 7 and 0 ndims
scalar = torch.tensor(7)

# scalar.item will return the nomral representaiton of that tensor
scalar.item()

7

In [15]:
#the .shape method will return the number of elements in each shape while ndim returns the number of dimensions that the tensor represents
matrix = torch.tensor([[[1,2], [3,4] , [1,2]]])
matrix.shape

torch.Size([1, 3, 2])

In [28]:
TENS = torch.rand(2,2,2)
TENS

tensor([[[0.6102, 0.7510],
         [0.8485, 0.7955]],

        [[0.9280, 0.9171],
         [0.7254, 0.5001]]])

In [30]:
torch.zeros(3,4), torch.ones(3,4)

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [37]:
num_range = torch.arange(1,20)
num_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [36]:
zero_range = torch.zeros_like(num_range)
zero_range

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
zero_range.dtype, zero_range.shape, zero_range.device

(torch.int64, torch.Size([19]), device(type='cpu'))

In [46]:
a = torch.rand(3,4)
b = torch.rand(3,4)

torch.matmul(a,b.T)

tensor([[1.3653, 0.8831, 0.6228],
        [2.2158, 1.6150, 0.8642],
        [1.6332, 0.9127, 0.5853]])

## Using GPUs for computation

In [6]:
# Setting up the device on which the code will run

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
tens = torch.tensor([1,2,3])
print(tens, tens.device)

tensor([1, 2, 3]) cpu


In [8]:
tens_on_gpu = tens.to(device)
tens_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
tens_back_on_cpu = tens_on_gpu.cpu().numpy()
tens_back_on_cpu

array([1, 2, 3], dtype=int64)